export const ofice = [
  {  
    id:'1',
    name:'Mrs.S.Manohari',
       quali:'B.Sc.,M.A.,M.Lib.Sci.,',
       desi:'PA to Principal',
       phn:'9443978059',
       email:'manohari.aravindhakshan@gmail.com'
  },

 { id:'2',
       name:'Mr.Al.Prabahar',
       quali:'B.com.,',
       desi:'Bursar',
       phn:'9443012999',
       email:'prabaharal@gmail.com'
  },
  { 
    id:'3',   
    name:'Mr.M.Karuppasamy',
    quali:'M.A (History)',
    desi:'Superintendent',
    phn:'9952568084',
    email:'mksamyaccet2015@gmail.com'
  },
  {  
    id:'4',   
    name:'Mrs.A.Badhurunnishal',
    quali:'M.A.,B.Ed.,M.Phil',
    desi:'Superintendent',
    phn:'9445381481',
    email:'badhurunnisharahumathulla@gmail.com'
  },     
  {
    id:'5',   
    name:'Mr.S.Ganesan',
    quali:'Hr.Sec.,NTC,NAC',
    desi:'Superintendent',
    phn:'9842526149',
    email:'ganesan1451065@gmail.com'
  },
  {
    id:'6',   
    name:'Mr.S.Abdul Majith',
    quali:'SSLC',
    desi:'Superintendent',
    phn:'7639636624',
    email:'samamajith1990@gmail.com'
  },
  {
    id:'7',   
    name:'Mrs.M.Vishnu Priya',
    quali:'B.Com',
    desi:'Superintendent',
    phn:'8838165526',
    email:'priyaworld333@gmail.com'
  },
 {
    id:'8',   
    name:'Mr.P.Adhisankar',
    quali:'B.Litt,M.A (Tamil)',
    desi:'Assistant',
    phn:'9677704237',
    email:'adhisankar49@gmail.com'
  },
  {
    id:'9',   
    name:'Mrs.B.Akila',
    quali:'M.Com.,B.Li.Sc.,',
    desi:'Assistant',
    phn:'9894053646',
    email:'akilarhiru2012@gmail.com'
  },
  {
    id:'10',   
    name:'Ms.S.Benazir Begum',
    quali:'B.A.,(English)',
    desi:'Assistant',
    phn:'8610995982',
    email:'benaziraccet@gmail.com'
  },
  {
    id:'11',   
    name:'Mr.K.Ganiselvam',
    quali:'M.A,B.Ed.,',
    desi:'Assistant',
    phn:'6382879145',
    email:'ganikalaiyur90@gmail.com'
  },
  {
    id:'12',   
    name:'Mr.S.Balagi',
    quali:'B.Sc.,(Chemistry)',
    desi:'Assistant',
    phn:'866757092',
    email:'balagironaldhinho@gmail.com'
  },
  {
    id:'13',   
    name:'Mr.S.Sheik Abdullah',
    quali:'B.E,(Aeronautical Engineering)',
    desi:'Assistant',
    phn:'9677474525',
    email:'sheikabdullah.aero@gmail.coom'
  },
  {
    id:'14',   
    name:'Mr.M.Saravanakumar',
    quali:'B.Sc.,(Chemistry)',
    desi:'Assistant',
    phn:'',
    email:''
  },
  {
    id:'15',   
    name:'Mr.N.Balaji',
    quali:'B.E(EEE)',
    desi:'Assistant',
    phn:'',
    email:''
  },
  {
    id:'16',   
    name:'Mrs.M.Sumathi',
    quali:'B.A.,(History)',
    desi:'Steno Typist',
    phn:'9629554985',
    email:'msumathi2401@gmail.com'
  },
  {
    id:'17',   
    name:'Ms.M.Mahalakshmi',
    quali:'Hr.Sec.,',
    desi:'Steno Typist',
    phn:'9751815926',
    email:'marimahendran73@gmail.com'
  },
  {
    id:'18',   
    name:'Mr.S.Prasanth',
    quali:'M.Sc.,(Computer Science)',
    desi:'Junior Assistant',
    phn:'9943809183',
    email:'prasanthjai333@gmail.com'
  },
  {
    id:'19',   
    name:'Ms.S.Sugirtha',
    quali:'B.Tech.,(Information Technology)',
    desi:'Junior Assistant',
    phn:'9894341456',
    email:'sugirthajesus37@gmail.com'
  },
  {
    id:'20',   
    name:'Mr.M.Balamurali',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:'murali.bala786@gmail.com'
  },
  {
    id:'21',   
    name:'Mrs.A.Jebakani',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:'jebakanisuthish@gmail.com'
  },
  {
    id:'22',   
    name:'Mrs.P.Sarala',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:'saralarajkumar77@gmail.com'
  },
  {
    id:'23',   
    name:'Mr.L.Arun',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:'visu3579@gmail.com'
  },
  {
    id:'24',   
    name:'Mr.PL.Karthikeyan',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:''
  },
  {
    id:'25',   
    name:'Mr.J.Syed Abudahir',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:''
  },
  {
    id:'26',   
    name:'Mr.P.Giridharan',
    quali:'',
    desi:'',
    phn:'',
    email:''
  },
  {
    id:'27',   
    name:'Mrs.R.Valarmathi',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:''
  },
  {
    id:'28',   
    name:'Mr.G.Thiagarajan',
    quali:'',
    desi:'',
    phn:'',
    email:''
  },
  {
    id:'29',   
    name:'Mr.V.Saravanakumar',
    quali:'',
    desi:'Junior Assistant',
    phn:'',
    email:''
  },
  {
    id:'30',   
    name:'Ms.M.Suguna',
    quali:'',
    desi:'Typist',
    phn:'',
    email:'sugunabe1844@gmail.com'
  },
  {
    id:'31',   
    name:'Mr.B.Periyasamy',
    quali:'',
    desi:'Record Asst.',
    phn:'',
    email:'periyasamy5500@gmail.com'
  },
  {
    id:'32',   
    name:'Mrs.T.Amutha',
    quali:'',
    desi:'Library Attender',
    phn:'',
    email:''
  },
  {
    id:'33',   
    name:'Mrs.S.Jayanthi',
    quali:'',
    desi:'Office Asst.(SG)',
    phn:'',
    email:'sjayanthi682@gmail.com'
  },
  {
    id:'34',   
    name:'Mr.P.Sivasankar',
    quali:'',
    desi:'Office Asst.(SG)',
    phn:'',
    email:'jayanthan2004@gmail.com'
  },
  {
    id:'35',   
    name:'Mr.S.Sembulingam',
    quali:'',
    desi:'ffice Asst.(SG)',
    phn:'',
    email:''
  },
  {
    id:'36',   
    name:'Mr.G.Velusamy',
    quali:'',
    desi:'Watchman(SG)',
    phn:'',
    email:''
  },
  {
    id:'37',   
    name:'Mr.S.Hariharan',
    quali:'',
    desi:'Watchman(SG)',
    phn:'',
    email:''
  },
  {
    id:'38',   
    name:'Mr.S.Murugan',
    quali:'',
    desi:'Watchman(SG)',
    phn:'',
    email:''
  },
  {
    id:'39',   
    name:'Mr.T.Vekatesan',
    quali:'',
    desi:'Watchman(SG)',
    phn:'',
    email:''
  },
  {
    id:'40',   
    name:'Mr.K.Palani',
    quali:'',
    desi:'Watchman(SG)',
    phn:'',
    email:''
  },
  {
    id:'41',   
    name:'Mr.PL.Vellaichamy',
    quali:'',
    desi:'Sweeper(SG)',
    phn:'',
    email:''
  },
  {
    id:'42',   
    name:'Mr.A.Nagarajan',
    quali:'',
    desi:'Sweeper(SG)',
    phn:'',
    email:''
  },
  {
    id:'43',   
    name:'Mr.M.Nallamani',
    quali:'',
    desi:'Marker(SG)',
    phn:'',
    email:''
  },
  {
    id:'44',   
    name:'Mr.T.Parthiban',
    quali:'',
    desi:'Cleaner',
    phn:'',
    email:''
  },
  {
    id:'45',   
    name:'Mrs.K.Banupriya',
    quali:'',
    desi:'Steno Typist',
    phn:'',
    email:''
  },
];
