export {default as Home} from './Home/Home'
export {default as Milestones} from './Milestone/Milestones'
export {default as About} from './About/About'
export {default as Vision} from './Vision/Vision'
export {default as Office} from './Office/Office'
export {default as Clubs} from './Clubs/Clubs'
export {default as Alumni} from './Alumni/Alumni'