export {default as Home} from './Home/Home'
export {default as Milestones} from './Milestone/Milestones'
export {default as About} from './About/About'
export {default as Vision} from './Vision/Vision'
export {default as Office} from './Office/Office'
export {default as Teqip1} from './Teqip1/Teqip1'
export {default as Teqip2} from './Teqip2/Teqip2'
export {default as Teqip3} from './Teqip3/Teqip3'