const subjects_list = {
    "CSE_subs": {
      "19CMG15": {credits: 4,subname:"Basic Civil and Mechanical Engineering"},
      "19ENH11": {credits: 3,subname:"Communicative English"},
      "19MAB12": {credits: 4,subname:"Mathematics I"},
      "19MEL18": {credits: 2,subname:"Workshop Practice Laboratory"},
      "19PHB14": {credits: 4,subname:"Physics: Optics and Semiconductors"},
      "19PHL17": {credits: 1.5,subname:"Physics Laboratory"},
  
      "19CHB21": {credits:4,subname:"Chemistry"},
      "19CHL26": {credits:1.5,subname:"Chemistry Laboratory"},
      "19CSG23": {credits:3,subname:"Python Programming"},
      "19CSL27": {credits:1.5,subname:"Python Programming Laboratory"},
      "19EEG16": {credits:4,subname:"Basic Electrical and Electronics Engineering"},
      "19MAB22": {credits:4,subname:"Mathematics II"},
      "19SHA01": {credits:0,subname:"Professional Communication"},
      "19SHA02": {credits:0,subname:"Error Analysis and Fundamental Physical Quantities"},
  
      "19CSC31": {credits:3,subname:"Programming and Data Structures"},
      "19CSC32": {credits:3,subname:"Database Management Systems"},
      "19CSH31": {credits:3,subname:"Professional Ethics and Human Values"},
      "19CSL31": {credits:1,subname:"Programming and Data Structures Laboratory"},
      "19CSL32": {credits:1,subname:"Database Management Systems Laboratory"},
      "19ECC43": {credits:3,subname:"Microprocessor and Microcontroller"},
      "19MAB31": {credits:4,subname:"Mathematics III"},
      "19NM018": {credits:2,subname:"Microsoft Office Fundamentals(Naan Mudhalvan Course)"},
      "19CHM31": {credits:0,subname:"Environmental Science and Engineering"},
  
      "19CSC41": {credits:3,subname:"Advanced Data Structures"},
      "19CSC42": {credits:3,subname:"Operating Systems"},
      "19CSC43": {credits:3,subname:"Computer Organization and Architecture"},
      "19CSC44": {credits:3,subname:"Design and Analysis of Algorithms"},
      "19CSG41": {credits:3,subname:"Analog and Digital Communication"},
      "19CSL41": {credits:1,subname:"Advanced Data Structures Laboratory"},
      "19CSL42": {credits:1,subname:"Operating Systems Laboratory"},
      "19MAB43": {credits:4,subname:"Discrete Mathematics"},
      "19NM023": {credits:2,subname:"Foundation for AI, ML, FS(Naan Mudhalvan Course)"},
      "19NM024": {credits:2,subname:"Network Essentials(Naan Mudhalvan Course)"},
  
      "19CSC51": { credits: 3, subname: "Software Engineering" },
      "19CSC52": { credits: 3, subname: "Computer Networks" },
      "19CSC53": { credits: 3, subname: "Theory of Computation" },
      "19CSC54": { credits: 3, subname: "OOPS and Java Programming"},
      "19CSE16": { credits: 3, subname: "XML and Web Technology"},
      "19CSE53": { credits: 3, subname: "Internet of Things"},
      "19CSL51": { credits: 1, subname: "Networks Laboratory"},
      "19CSL52": { credits: 1, subname: "OOPS and Java Programming Laboratory"},
      "19CSZ51": { credits: 1, subname: "Technical Seminar - I"},
      "19MAB51": { credits: 4, subname: "Probability and Queuing Theory"},
      "19CSC71": { credits: 3, subname: "Graphics and Multimedia" },
  
    "19CSC72": { credits: 3, subname: "C # and .NET Technologies" },
    "19CSC73": { credits: 3, subname: "Cryptography and Network Security" },
    "19CSE32": { credits: 3, subname: "Grid and Cloud Computing" },
    "19CSL71": { credits: 3, subname: "Graphics and Multimedia Laboratory" },
    "19CSL72": { credits: 1, subname: "C # and .NET Laboratory" },
    "19CSZ71": { credits: 3.5, subname: "Mini Project" },
    "19MEP04": { credits: 3, subname: "Principles of Management" },
    "19MEP05": { credits: 3, subname: "Supply Chain Management" },
  
    "22CSC32": { credits: 3, subname: "Database Management Systems" },
    "22CSC33": { credits: 3, subname: "Data Structures using C" },
    "22CSC35": { credits: 3, subname: "Object Oriented Programming using Java" },
    "22CSC36": { credits: 4, subname: "Algorithms" },
    "22CSG31": { credits: 4, subname: "Digital Principles and Computer Organization" },
    "22CSL37": { credits: 1.5, subname: "Data Structures Laboratory" },
    "22CSL38": { credits: 1.5, subname: "Object Oriented Programming Laboratory" },
    "22CSL39": { credits: 1.5, subname: "Database Management Systems Laboratory" },
    "22CSZ3A": { credits: 1, subname: "Professional Development (Skill Based Course)" },
    "22MAB34": { credits: 4, subname: "Discrete Mathematics" },
  
    "22HSE11": { credits: 3, subname: "Professional English-I" },
    "22MAB13": { credits: 4, subname: "Matrices, Calculus and Laplace Transforms" },
    "22PHB14": { credits: 3, subname: "Engineering Physics" },
    "22CYB15": { credits: 3, subname: "Engineering Chemistry" },
    "22CSG16": { credits: 3, subname: "Problem Solving and Python Programming" },
    "22HST17": { credits: 1, subname: "தமிழர் மரபு / Heritage of Tamils" },
    "22CSL18": { credits: 1.5, subname: "Problem Solving and Python Programming Laboratory" },
    "22PHL19": { credits: 1.5, subname: "Physics Laboratory" },
    "22CYL1A": { credits: 1.5, subname: "Chemistry Laboratory" },
    "22HSL1B": { credits: 1.5, subname: "English Laboratory" },
     
    },
    "EEE_subs": {
      "19CSC51": { credits: 3, subname: "Software Engineering" },
      "19CSC52": { credits: 3, subname: "Compiler Design" },
      "19CSC53": { credits: 3, subname: "Computer Networks" },
      "19CSC41": { credits: 3, subname: "Advanced Data Structres" },
      "19CSC42": { credits: 3, subname: "Operating System" },
      "19CSC43": { credits: 3, subname: "Computer Organization & Architecture" },
      "19CSC31": { credits: 3, subname: "Programming & Data Structres" },
    },
  };
  
  module.exports=subjects_list