export {default as Navigation} from './Navigation/Navigation';
export {default as Footer} from './Footer/Footer';
export {default as Heroimage} from './Heroimage/Heroimage';
export {default as Heroimagecarousal} from './Heroimagecarousal/Heroimagecarousal';
export {default as Slideshow} from './Slideshow/Slideshow';
export {default as Table} from './Table/Table';
export {default as Modal_carousel} from './Modal_carousel/Modal_carousel';
export {default as Profile_display} from './Profile_display/Profile_display';
export {default as Timeline} from './Timeline/Timeline';
export {default as Listformat} from './Listformat/Listformat';
export {default as Radial_menu} from './Radial_menu/Radial_menu';
export {default as Hodmsg} from './Hodmsg/Hodmsg';
export {default as Sh_tabs} from './Sh_tabs/Sh_tabs'
export {default as Sh_tab_faculty} from './Sh_tabs/Sh_tab_faculty'
export {default as Sh_tab_lab} from './Sh_tabs/Sh_tab_lab'
export {default as Sh_tab_research} from './Sh_tabs/Sh_tab_research'
export {default as Sh_tab_Programme} from './Sh_tabs/Sh_tab_Programme'