export {default as Home} from './Home/Home'
export {default as Milestones} from './Milestone/Milestones'
export {default as About} from './About/About'
export {default as Vision} from './Vision/Vision'
export {default as Office} from './Office/Office'
export {default as Clubs} from './Clubs/Clubs'
export {default as Alumni} from './Alumni/Alumni'
export {default as Nss} from './Nss/Nss'
export {default as Ncc} from './Ncc/Ncc'
export {default as Teqip1} from './Teqip1/Teqip1'
export {default as Teqip2} from './Teqip2/Teqip2'
export {default as Teqip3} from './Teqip3/Teqip3'
export {default as Programs_offered} from './Programs_offered/Programs_offered'
export {default as Life} from './Life/Life'
export {default as T3_officials} from './T3_officials/T3_officials'
export {default as T3_acad} from './T3_acad/T3_acad'
export {default as T3_procure} from './T3_procure/T3_procure'
export {default as T3_twin} from './T3_twin/T3_twin'
export {default as Govern} from './Govern/Govern'
export {default as Aicte} from './Aicte/Aicte'
export {default as Organisation} from './Organisation/Organisation'
export {default as Under} from './Under/Under'
export {default as Thiran} from './Thiran/Thiran'
export {default as Sports} from './Sports/Sports'
export {default as Csedept} from './Csedept/Csedept'
export {default as Ecedept} from './Ecedept/Ecedept'
export {default as Ece_peo} from './Ecedept/Ece_peo'
export {default as Ece_faculties} from './Ecedept/Ece_faculties'
export {default as Ece_lab} from './Ecedept/Ece_lab'
export {default as Ece_research} from './Ecedept/Ece_research'
export {default as Ece_rankers} from './Ecedept/Ece_rankers'
export {default as Mech_rankers} from './Mechdept/Mech_rankers'
export {default as Ece_events} from './Ecedept/Ece_events'
export {default as Ece_projects} from './Ecedept/Ece_projects'
export {default as Ece_stud_activity} from './Ecedept/Ece_stud_activity'
export {default as Ece_antenna} from './Ecedept/Ece_antenna'
export {default as Annual_report} from './Annual_Report/Annual_report'
export {default as Academic} from './Academic/Academic'
export {default as Fees} from './Fees/Fees'
export {default as Cse_faculties} from './Csedept/Cse_faculties'
export {default as Civildept} from './Civildept/Civildept'
export {default as Mechdept} from './Mechdept/Mechdept'
export {default as Eeedept} from './Eeedept/Eeedept'
export {default as Cse_peo} from './Csedept/Cse_peo'
export {default as Cse_lab} from './Csedept/Cse_lab'
export {default as Cse_events} from './Csedept/Cse_events'
export {default as Cse_prog_org} from './Csedept/Cse_prog_org'
export {default as Cse_mou} from './Csedept/Cse_mou'
export {default as Civil_peo} from './Civildept/Civil_peo'
export {default as Civil_faculties} from './Civildept/Civil_faculties'
export {default as Civil_lab} from './Civildept/Civil_lab'
export {default as Civil_events} from './Civildept/Civil_events'
export {default as Civil_magazine} from './Civildept/Civil_magazine'
export {default as Civil_indus} from './Civildept/Civil_indus'
export {default as Mech_peo} from './Mechdept/Mech_peo'
export {default as Mech_faculties} from './Mechdept/Mech_faculties'
export {default as Mech_lab} from './Mechdept/Mech_lab'
export {default as Mech_events} from './Mechdept/Mech_events'
export {default as Eee_peo} from './Eeedept/Eee_peo'
export {default as Eee_faculties} from './Eeedept/Eee_faculties'
export {default as Eee_lab} from './Eeedept/Eee_lab'
export {default as Eee_events} from './Eeedept/Eee_events'
export {default as Eee_modern} from './Eeedept/Eee_modern'
export {default as Ece_placement} from './Ecedept/Ece_placement'
export {default as Iqac} from './Iqac/Iqac'
export {default as Iqac_min} from './Iqac_min/Iqac_min'
export {default as Iqac_aqar} from './Iqac_aqar/Iqac_aqar'
export {default as Iqac_feed} from './Iqac_feed/Iqac_feed'
export {default as Iqac_distinctiveness} from './Iqac_distinctiveness/Iqac_distinctiveness'
export {default as Iqac_practices} from './Iqac_practices/Iqac_practices'
export {default as Iqac_std_statisfy} from './Iqac_std_statisfy/Iqac_std_statisfy'
export {default as Iqac_committee} from './Iqac_committee/Iqac_committee'


export {default as Nba} from './Nba/Nba'
export {default as Nbadoc} from './Nba/Nbadoc'
export {default as Nba_sar} from './Nba/Nba_sar'
export {default as Nirf} from './Nirf/Nirf'
export {default as Iic} from './Iic/Iic'
export {default as Scholarship} from './Scholarship/Scholarship'
export {default as Civil_awards} from './Civildept/Civil_awards'
export {default as Ece_dept_lib} from './Ecedept/Ece_dept_lib'
export {default as Iste} from './Iste/Iste'
export {default as Uba} from './Uba/Uba'
export {default as Sih} from './Sih/Sih'
export {default as Committee} from './Committee/Committee'
export {default as Yrc} from './Yrc/Yrc'
export {default as Devpage} from './Devpage/Devpage'
export {default as Eee_research} from './Eeedept/Eee_research'
export {default as Eee_nextgen} from './Eeedept/Eee_nextgen'
export {default as Civil_library} from './Civildept/Civil_library'
export {default as Civil_placement} from './Civildept/Civil_placement'
export {default as Civil_internal} from './Civildept/Civil_internal'
export {default as Civil_research} from './Civildept/Civil_research'
export {default as Facilities} from './Facilities/Facilities'
export {default as Eee_lib} from './Eeedept/Eee_lib'
export {default as Eee_studcorner} from './Eeedept/Eee_studcorner'
export{default as Mech_lib} from './Mechdept/Mech_lib'
export{default as Mech_phd} from'./Mechdept/Mech_phd'
export{default as Mech_org} from'./Mechdept/Mech_org'
// export{default as Placement} from './Placement/placement'
export{default as Mech_coe} from './Mechdept/Mech_coe'
export{default as Coe} from './coe/Coe'
export{default as Coe_Adminstration}from'./coe/Coe_Adminstration'
export {default as Coe_Academic}from'./coe/Coe_Academic'
export {default as Coe_link}from'./coe/Coe_link'
export {default as Coe_Contact}from'./coe/Coe_Contact'
export {default as Coe_Application}from'./coe/Coe_Application'
export {default as Coe_Claim}from'./coe/Coe_Claim'
export {default as Coe_FeeStruct}from'./coe/Coe_FeeStruct'
export {default as Coe_syllabuss}from'./coe/Coe_syllabuss'

export {default as Coe_syllabus1}from'./coe/Coe_syllabus1'
export {default as Coe_Committiee}from'./coe/Coe_Committiee'
export{default as Placement} from './placement/placement'
export {default as Placement_faq} from './placement/Placement_Faq'
export {default as Placement_wk_training} from './placement/Placement_wk_training'
export {default as Placement_stats} from './placement/Placement_stats'

// export{default as Mech_coe} from'./Mechdept/Mech_coe'
export{default as Login} from './Login/Login'
export{default as Dashboard} from './Dashboard/Dashboard'
export{default as Dash_results} from './Dashboard/Dash_results'
export{default as Logout} from './Logout/Logout'
export{default as Passreset} from './Passreset/Passreset'
export{default as Otp} from './Otp/Otp'
export{default as Newpass} from './Newpass/Newpass'
export{default as Admin_dashboard} from './Admin_dashboard/Admin_dashboard'


export{default as Research} from './Research/Research'

export{default as Physicsdept} from './Physicsdept/Physicsdept'
export {default as Physics_faculty} from './Physicsdept/Physics_faculty'
export {default as Physics_lab_facility} from './Physicsdept/Physics_lab_facility'
export {default as Physics_research} from './Physicsdept/Physics_research'
export {default as Physics_programme} from './Physicsdept/Physics_programme'
export {default as Physics_former_prof} from './Physicsdept/Physics_former_prof'

export{default as Chemistrydept} from './Chemistrydept/Chemistrydept'
export {default as Chemistry_faculty} from './Chemistrydept/Chemistry_faculty'
export {default as Chemistry_lab_facility} from './Chemistrydept/Chemistry_lab_facility'
export {default as Chemistry_research} from './Chemistrydept/Chemistry_research'
export {default as Chemistry_programme} from './Chemistrydept/Chemistry_programme'

export{default as Mathsdept} from './Mathsdept/Mathsdept'
export {default as Maths_faculty} from './Mathsdept/Maths_faculty'
export {default as Maths_lab_facility} from './Mathsdept/Maths_lab_facility'
export {default as Maths_research} from './Mathsdept/Maths_research'
export {default as Maths_programme} from './Mathsdept/Maths_programme'

export{default as Englishdept} from './Englishdept/Englishdept'
export {default as English_faculty} from './Englishdept/English_faculty'
export {default as English_lab_facility} from './Englishdept/English_lab_facility'
export {default as English_research} from './Englishdept/English_research'
export {default as English_programme} from './Englishdept/English_programme'

export{default as Naac} from './Naac/Naac'
export{default as Rti} from './Rti/Rti'
export{default as Ignatz} from './Sports/Ignatz'
export{default as Typhonz_page} from './Sports/Typhonz_page'
export{default as Phoenix} from './Sports/Phoenix'
export{default as Akkadians} from './Sports/Akkadians'

export{default as Audit_stmt} from './Audit_stmt/Audit_stmt'
export{default as Verification} from './Verification/Verification'
export{default as Iqac_strategic} from './Iqac_strategic/Iqac_strategic'
export{default as Autonomous} from './Autonomous/Autonomous'

export {default as Build}from'./Clubs/Build'
export{default as Ece_coe} from './Ecedept/Ece_coe'
