export const sidenav=[
  {
  id:"1",
  dashboard_path1:"/dashboard",
  dashboard_name1:"Profile",
},
{
  id:"2",
  dashboard_path1:"/results",
  dashboard_name1:"Result",
},


]

export const subjects = {
  "CSE_subs": {
    "19CMG15": {credits: 4,subname:"Basic Civil and Mechanical Engineering"},
    "19ENH11": {credits: 3,subname:"Communicative English"},
    "19MAB12": {credits: 4,subname:"Mathematics I"},
    "19MEL18": {credits: 2,subname:"Workshop Practice Laboratory"},
    "19PHB14": {credits: 4,subname:"Physics: Optics and Semiconductors"},
    "19PHL17": {credits: 1.5,subname:"Physics Laboratory"},

    "19CHB21": {credits:4,subname:"Chemistry"},
    "19CHL26": {credits:1.5,subname:"Chemistry Laboratory"},
    "19CSG23": {credits:3,subname:"Python Programming"},
    "19CSL27": {credits:1.5,subname:"Python Programming Laboratory"},
    "19EEG16": {credits:4,subname:"Basic Electrical and Electronics Engineering"},
    "19MAB22": {credits:4,subname:"Mathematics II"},
    "19SHA01": {credits:0,subname:"Professional Communication"},
    "19SHA02": {credits:0,subname:"Error Analysis and Fundamental Physical Quantities"},

    "19CSC31": {credits:3,subname:"Programming and Data Structures"},
    "19CSC32": {credits:3,subname:"Database Management Systems"},
    "19CSH31": {credits:3,subname:"Professional Ethics and Human Values"},
    "19CSL31": {credits:1,subname:"Programming and Data Structures Laboratory"},
    "19CSL32": {credits:1,subname:"Database Management Systems Laboratory"},
    "19ECC43": {credits:3,subname:"Microprocessor and Microcontroller"},
    "19MAB31": {credits:4,subname:"Mathematics III"},
    "19NM018": {credits:2,subname:"Microsoft Office Fundamentals(Naan Mudhalvan Course)"},
    "19CHM31": {credits:0,subname:"Environmental Science and Engineering"},

    "19CSC41": {credits:3,subname:"Advanced Data Structures"},
    "19CSC42": {credits:3,subname:"Operating Systems"},
    "19CSC43": {credits:3,subname:"Computer Organization and Architecture"},
    "19CSC44": {credits:3,subname:"Design and Analysis of Algorithms"},
    "19CSG41": {credits:3,subname:"Analog and Digital Communication"},
    "19CSL41": {credits:1,subname:"Advanced Data Structures Laboratory"},
    "19CSL42": {credits:1,subname:"Operating Systems Laboratory"},
    "19MAB43": {credits:4,subname:"Discrete Mathematics"},
    "19NM023": {credits:2,subname:"Foundation for AI, ML, FS(Naan Mudhalvan Course)"},
    "19NM024": {credits:2,subname:"Network Essentials(Naan Mudhalvan Course)"},
    "19NM020": {credits:2,subname:"Block Chain Technology (Naan Mudhalvan Course)"},

    "19CSC51": { credits: 3, subname: "Software Engineering" },
    "19CSC52": { credits: 3, subname: "Computer Networks" },
    "19CSC53": { credits: 3, subname: "Theory of Computation" },
    "19CSC54": { credits: 3, subname: "OOPS and Java Programming"},
    "19CSE16": { credits: 3, subname: "XML and Web Technology"},
    "19CSE53": { credits: 3, subname: "Internet of Things"},
    "19CSL51": { credits: 1, subname: "Networks Laboratory"},
    "19CSL52": { credits: 1, subname: "OOPS and Java Programming Laboratory"},
    "19CSZ51": { credits: 1, subname: "Technical Seminar - I"},
    "19MAB51": { credits: 4, subname: "Probability and Queuing Theory"},
    "19CSC71": { credits: 3, subname: "Graphics and Multimedia" },

  "19CSC72": { credits: 3, subname: "C # and .NET Technologies" },
  "19CSC73": { credits: 3, subname: "Cryptography and Network Security" },
  "19CSE32": { credits: 3, subname: "Grid and Cloud Computing" },
  "19CSL71": { credits: 3, subname: "Graphics and Multimedia Laboratory" },
  "19CSL72": { credits: 1, subname: "C # and .NET Laboratory" },
  "19CSZ71": { credits: 3.5, subname: "Mini Project" },
  "19MEP04": { credits: 3, subname: "Principles of Management" },
  "19MEP05": { credits: 3, subname: "Supply Chain Management" },

  "22IPM01":{credits:0, subname: "Orientation Program"},

  "22CSC32": { credits: 3, subname: "Database Management Systems" },
  "22CSC33": { credits: 3, subname: "Data Structures using C" },
  "22CSC35": { credits: 3, subname: "Object Oriented Programming using Java" },
  "22CSC36": { credits: 4, subname: "Algorithms" },
  "22CSG31": { credits: 4, subname: "Digital Principles and Computer Organization" },
  "22CSL37": { credits: 1.5, subname: "Data Structures Laboratory" },
  "22CSL38": { credits: 1.5, subname: "Object Oriented Programming Laboratory" },
  "22CSL39": { credits: 1.5, subname: "Database Management Systems Laboratory" },
  "22CSZ3A": { credits: 1, subname: "Professional Development (Skill Based Course)" },
  "22MAB34": { credits: 4, subname: "Discrete Mathematics" },

  "22HSE11": { credits: 3, subname: "Professional English-I" },
  "22MAB13": { credits: 4, subname: "Matrices, Calculus and Laplace Transforms" },
  "22PHB14": { credits: 3, subname: "Engineering Physics" },
  "22CYB15": { credits: 3, subname: "Engineering Chemistry" },
  "22CSG16": { credits: 3, subname: "Problem Solving and Python Programming" },
  "22HST17": { credits: 1, subname: "தமிழர் மரபு / Heritage of Tamils" },
  "22CSL18": { credits: 1.5, subname: "Problem Solving and Python Programming Laboratory" },
  "22PHL19": { credits: 1.5, subname: "Physics Laboratory" },
  "22CYL1A": { credits: 1.5, subname: "Chemistry Laboratory" },
  "22HSL1B": { credits: 1.5, subname: "English Laboratory" },
   
  },
  "EEE_subs": {
    "19CSC51": { credits: 3, subname: "Software Engineering" },
    "19CSC52": { credits: 3, subname: "Compiler Design" },
    "19CSC53": { credits: 3, subname: "Computer Networks" },
    "19CSC41": { credits: 3, subname: "Advanced Data Structres" },
    "19CSC42": { credits: 3, subname: "Operating System" },
    "19CSC43": { credits: 3, subname: "Computer Organization & Architecture" },
    "19CSC31": { credits: 3, subname: "Programming & Data Structres" },

    "19CMG15": {credits: 4,subname:"Basic Civil and Mechanical Engineering"},
    "19ENH11": {credits: 3,subname:"Communicative English"},
    "19MAB12": {credits: 4,subname:"Mathematics I"},
    "19MEL18": {credits: 2,subname:"Workshop Practice Laboratory"},
    "19PHB14": {credits: 4,subname:"Physics: Optics and Semiconductors"},
    "19PHL17": {credits: 1.5,subname:"Physics Laboratory"},

    "19CHB21": {credits:4,subname:"Chemistry"},
    "19CHL26": {credits:1.5,subname:"Chemistry Laboratory"},
    "19CSG23": {credits:3,subname:"Python Programming"},
    "19CSL27": {credits:1.5,subname:"Python Programming Laboratory"},
    "19MAB22": {credits:4,subname:"Mathematics II"},
    "19MEG24": {credits:3,subname:"Engineering Graphics" },
    "19SHA01": {credits:0,subname:"Professional Communication"},
    "19SHA02": {credits:0,subname:"Error Analysis and Fundamental Physical Quantities"},

    "19EEC31": {credits:4,subname:"Electric Circuit Analysis"},
    "19EEC32": {credits:3,subname:"Analog Electronics"},
    "19EEG31": {credits:3,subname:"Electromagnetic Theory"},
    "19EEG32": {credits:3,subname:"Measurements and Instrumentation"},
    "19EEL31": {credits:1.5,subname:"electric Circuits Laboratory"},
    "19EEL32": {credits:1.5,subname:"Analog Electronics Laboratory"},
    "19MAB31": {credits:4,subname:"Mathematics III"},
    "19NM018": {credits:2,subname:"Microsoft Office Fundamentals(Naan Mudhalvan Course)"},
    "19CHM31": {credits:0,subname:"Environmental Science and Engineering"},

    "19EEC41":{credits:4,subname:"D.C Machines and Transformers"},
    "19EEC42":{credits:4,subname:"Generation, Transmission and Distribution"},
    "19EEC43":{credits:3,subname:"Digital Logic Circuits"},
    "19EEC44":{credits:3,subname:"Analog Integrated Circuits and Appliations"},
    "19EEL41":{credits:1.5,subname:"D.C Machines and Transformers Laboratory"},
    "19EEL42":{credits:1.5,subname:"Analog and Digital Integrated Circuits Laboratory"},
    "19MAB41":{credits:3,subname:"Numerical Methods"},
    "19NM019": {credits:2,subname:"Robotic Process and Industrial Automation (Naan Mudhalvan Course)"},

    "19EEG51":{credits:4,subname:"Control System"},
    "19EEC51":{credits:4,subname:"AC Machines"},
    "19EEC52":{credits:3,subname:"Analysis of Signals and Systems"},
    "19EEP05":{credits:3,subname:"Internet of Things And its Applications"},
    "19EEE07":{credits:3,subname:"Electrical Energy Utilization and conservation"},
    "19EEE18":{credits:3,subname:"Electrical Safety Management and Energy Audit (FT)"},
    "19EEL51":{credits:1.5,subname:"Control and Instrumentation Laboratory"},
    "19EEL52":{credits:1.5,subname:"A.C Machines Laboratory"},
    "19EEZ51":{credits:3,subname:"Mini Project"},

    "22MAB32": {credits: 4, subname: "Probability Complex Functions and Fourier Series"},
    "22ECG31": {credits: 4, subname: "Signals and Systems"},
    "22EEC33": {credits: 4, subname: "Electrical Machines - I"},
    "22EEC34": {credits: 3, subname: "Electronic Devices and Circuits"},
    "22EEC35": {credits: 3, subname: "Electromagnetic Fields"},
    "22EEG36": {credits: 3, subname: "C Programming and Data Structures"},
    "22EEL37": {credits: 1.5, subname: "Electronic Devices and Circuits Laboratory"},
    "22EEL38": {credits: 1.5, subname: "C Programming and Data Structures Laboratory"},
    "22EEL3A": {credits: 1.5, subname: "Electrical Machines Laboratory - I"},
    "22EEZ39": {credits: 1, subname: "Professional Development (Skill Based Course)"},

    "22HSE11": {credits: 3, subname: "Professional English-I"},
    "22MAB13": {credits: 4, subname: "Matrices, Calculus and Laplace Transforms"},
    "22PHB14": {credits: 3, subname: "Engineering Physics"},
    "22CYB15": {credits: 3, subname: "Engineering Chemistry"},
    "22CSG16": {credits: 3, subname: "Problem Solving and Python Programming"},
    "22HST17": {credits: 1, subname: "தமிழர் மரபு / Heritage of Tamils"},
    "22CSL18": {credits: 1.5, subname: "Problem Solving and Python Programming Laboratory"},
    "22PHL19": {credits: 1.5, subname: "Physics Laboratory"},
    "22CYL1A": {credits: 1.5, subname: "Chemistry Laboratory"},
    "22HSL1B": {credits: 1.5, subname: "English Laboratory"},
  },
  "ECE_subs": {
    "19CMG15": {credits: 4,subname:"Basic Civil and Mechanical Engineering"},
    "19ENH11": {credits: 3,subname:"Communicative English"},
    "19MAB12": {credits: 4,subname:"Mathematics I"},
    "19MEL18": {credits: 2,subname:"Workshop Practice Laboratory"},
    "19PHB14": {credits: 4,subname:"Physics: Optics and Semiconductors"},
    "19PHL17": {credits: 1.5,subname:"Physics Laboratory"},

    "19CHB21": {credits:4,subname:"Chemistry"},
    "19CHL26": {credits:1.5,subname:"Chemistry Laboratory"},
    "19CSG23": {credits:3,subname:"Python Programming"},
    "19CSL27": {credits:1.5,subname:"Python Programming Laboratory"},
    "19EEG25": {credits:3,subname:"Basic Electrical Engineering"},
    "19MAB22": {credits:4,subname:"Mathematics II"},
    "19SHA01": {credits:0,subname:"Professional Communication"},
    "19SHA02": {credits:0,subname:"Error Analysis and Fundamental Physical Quantities"},

    "19ECB32": {credits:4,subname:"Time Harmonic Electromagnetic Fields"},
    "19ECC31": {credits:3,subname:"Digital Electronics"},
    "19ECC32": {credits:3,subname:"Electronic Circuits-I"},
    "19ECG31": {credits:4,subname:"Signals and Systems"},
    "19ECL31": {credits:1,subname:"Electron Devices and Circuits Laboratory"},
    "19ECL32": {credits:1,subname:"Digital Electronics Laboratory"},
    "19MAB31": {credits:4,subname:"Mathematics III"},
    "19NM018": {credits:2,subname:"Microsoft Office Fundamentals(Naan Mudhalvan Course)"},
    "19CHM31": {credits:0,subname:"Environmental Science and Engineering"},

    "19ECC41": {credits:3,subname:"Electronic Circuits-II"},
    "19ECC42": {credits:3,subname:"RF Transmission Lines"},
    "19ECC43": {credits:3,subname:"Microprocessor and Microcontoller"},
    "19ECH41": {credits:3,subname:"Professional Ethics and Human Values"},
    "19ECL41": {credits:1,subname:"Electronic Circuits and Simulation Laboratory"},
    "19ECL42": {credits:1,subname:"Microprocessor and Microcontoller Laboratory"},
    "19EEG51": {credits:4,subname:"Control Systems"},
    "19MAB42": {credits:4,subname:"Probability and Random Processes"},
    "19NM019": {credits:2,subname:"Robotic Process and Industrial Automation (Naan Mudhalvan Course)"},
    "19NM020": {credits:2,subname:"Block Chain Technology (Naan Mudhalvan Course)"},
    "19NM021": {credits:2,subname:"Digital Marketing (Naan Mudhalvan Course)"},

    "19ECC51": {credits: 4, subname: "Digital Signal Processing"},
    "19ECC52": {credits: 3, subname: "Linear Integrated Circuits"},
    "19ECC53": {credits: 3, subname: "Communication Theory"},
    "19ECC54": {credits: 3, subname: "Antennas and Wave Propagation"},
    "19MEH41": {credits: 3, subname: "Total Quality Management"},
    "19ECE01": {credits: 3, subname: "Network Analysis & Synthesis"},
    "19ECE03": {credits: 3, subname: "Measurements and Instrumentation"},
    "19ECE04": {credits: 3, subname: "Image Processing"},
    "19ECE06": {credits: 3, subname: "Medical Electronics"},
    "19ECL51": {credits: 1, subname: "Digital Signal Processing Laboratory"},
    "19ECL52": {credits: 1, subname: "Linear Integrated Circuits Laboratory"},
    "19ECZ51": {credits: 1, subname: "Technical Seminar I"},

    "22MAB33": { credits: 4, subname: "Random Processes and Linear Algebra "},
    "22ECC31": { credits: 4, subname: "Signals and Systems"},
    "22ECC32": { credits: 4, subname: "Digital Systems Design"},
    "22ECC34": { credits: 3, subname: "Electron Devices and Circuits"},
    "22ECC35": { credits: 3, subname: "Electromagnetic Field Theory"},
    "22ECG36": { credits: 3, subname: "C Programming and Data Structures"},
    "22ECL37": { credits: 1.5, subname: "Electron Devices and Circuits Laboratory"},
    "22ECL38": { credits: 1.5, subname: "C Programming and Data Structures  Laboratory"},
    "22ECZ39": { credits: 1, subname: "Professional Development"},

    "22HSE11": {credits: 3, subname: "Professional English-I"},
    "22MAB13": {credits: 4, subname: "Matrices, Calculus and Laplace Transforms"},
    "22PHB14": {credits: 3, subname: "Engineering Physics"},
    "22CYB15": {credits: 3, subname: "Engineering Chemistry"},
    "22CSG16": {credits: 3, subname: "Problem Solving and Python Programming"},
    "22HST17": {credits: 1, subname: "தமிழர் மரபு / Heritage of Tamils"},
    "22CSL18": {credits: 1.5, subname: "Problem Solving and Python Programming Laboratory"},
    "22PHL19": {credits: 1.5, subname: "Physics Laboratory"},
    "22CYL1A": {credits: 1.5, subname: "Chemistry Laboratory"},
    "22HSL1B": {credits: 1.5, subname: "English Laboratory"},
  },

  "MEC_subs": {

    "19MEC51": {credits: 3, subname: "Design of Machine Elements"},
    "19MEC52": {credits: 3, subname: "Theory of Machines II"},
    "19MEC53": {credits: 3, subname: "Fluid Machinery"},
    "19MEH51": {credits: 3, subname: "Engineering Economics and Cost Analysis"},
    "19EEP01": {credits: 3, subname: "Renewable Energy Resources"},
    "19MEP04": {credits: 3, subname: "Principles of Management"},
    "19MEE26": {credits: 3, subname: "Industrial Engineering and Management"},
    "19MEE08": {credits: 3, subname: "Design of Electric Vehicles"},
    "19MEE13": {credits: 3, subname: "Automobile Engineering"},
    "19MEE15": {credits: 3, subname: "Process Planning and Cost Estimation"},
    "19MEE17": {credits: 3, subname: "Welding and Casting Process"},
    "19MEL51": {credits: 1.5, subname: "Theory of Machines Laboratory"},
    "19MEL52": {credits: 1.5, subname: "Fluid Mechanics and Machinery Laboratory"},

    "22MAB31": {credits: 4, subname: "Transforms and Partial Differential Equations"},
    "22MEG32": {credits: 3, subname: "Engineering Mechanics"},
    "22MEC33": {credits: 3, subname: "Engineering Thermodynamics"},
    "22MEG34": {credits: 4, subname: "Fluid Mechanics and Machinery"},
    "22MEC35": {credits: 3, subname: "Engineering Materials and Metallurgy"},
    "22MEC36": {credits: 3, subname: "Manufacturing Processes"},
    "22MEL37": {credits: 2, subname: "Computer Aided Machine Drawing Laboratory"},
    "22MEL38": {credits: 2, subname: "Manufacturing Technology Laboratory"},
    "22MEZ39": {credits: 1, subname: "Professional Development"},

    "22HSE11": {credits: 3, subname: "Professional English-I"},
    "22MAB13": {credits: 4, subname: "Matrices, Calculus and Laplace Transforms"},
    "22PHB14": {credits: 3, subname: "Engineering Physics"},
    "22CYB15": {credits: 3, subname: "Engineering Chemistry"},
    "22CSG16": {credits: 3, subname: "Problem Solving and Python Programming"},
    "22HST17": {credits: 1, subname: "தமிழர் மரபு / Heritage of Tamils"},
    "22CSL18": {credits: 1.5, subname: "Problem Solving and Python Programming Laboratory"},
    "22PHL19": {credits: 1.5, subname: "Physics Laboratory"},
    "22CYL1A": {credits: 1.5, subname: "Chemistry Laboratory"},
    "22HSL1B": {credits: 1.5, subname: "English Laboratory"}
  },

  "CIV_subs": {

    "19CEC51": {credits: 4, subname: "Structural Analysis I"},
    "19CEC52": {credits: 4, subname: "Design of RC Elements"},
    "19CEC53": {credits: 3, subname: "Irrigation Engineering and Hydraulic Structures"},
    "19CEC54": {credits: 3, subname: "Environmental Engineering I"},
    "19CEC55": {credits: 3, subname: "Foundation Engineering"},
    "19CEL51": {credits: 1.5, subname: "Environmental Engineering Laboratory"},
    "19CEL52": {credits: 1.5, subname: "Building Material Laboratory"},

    "22MAB31": {credits: 4, subname: "Transforms and Partial Differential Equation"},
    "22CEG32": {credits: 3, subname: "Engineering Mechanics"},
    "22CEG33": {credits: 3, subname: "Fluid Mechanics"},
    "22CEC34": {credits: 3, subname: "Construction Materials and Technology"},
    "22CEC35": {credits: 3, subname: "Surveying-I"},
    "22CEC36": {credits: 3, subname: "Water Supply Engineering"},
    "22CEL37": {credits: 1.5, subname: "Survey Laboratory I"},
    "22CEL38": {credits: 1.5, subname: "Computer Aided Building Drawing"},
    "22CEL39": {credits: 1.5, subname: "Environmental Engineering Laboratory"},
    "22CEZ3A": {credits: 1, subname: "Professional Development"},

    "22HSE11": {credits: 3, subname: "Professional English-I"},
    "22MAB12": {credits: 4, subname: "Matrices and Calculus"},
    "22PHB14": {credits: 3, subname: "Engineering Physics"},
    "22CYB15": {credits: 3, subname: "Engineering Chemistry"},
    "22EEG16": {credits: 3, subname: "Basic Electrical, Electronics and Instrumentation Engineering"},
    "22HST17": {credits: 1, subname: "தமிழர் மரபு / Heritage of Tamils"},
    "22EEL18": {credits: 1.5, subname: "Basic Electrical and Electronics Engineering Laboratory"},
    "22PHL19": {credits: 1.5, subname: "Physics Laboratory"},
    "22CYL1A": {credits: 1.5, subname: "Chemistry Laboratory"},
    "22HSL1B": {credits: 1.5, subname: "English Laboratory"},
  }
};

export const admin_menu = [
  {
    id: "1",
    path: "/admin-panel",
    link: "excel to database",
    arl: "l",
  },
];
